kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: default_endpoint1
  version: 1.0
  namespace: dev
spec:
  url: http://test.com
  method: GET
  connectTimeout: 300
  readTimeout: 200
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    truststoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""
