#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: PolicySequence
apiVersion: api.webmethods.io/v1
metadata:
  name: my_policies
  version: 1.0
  namespace: policies
  tags:
    - my_policies
spec:
  transport:
    - $ref: dev:enable_https:1.0
  routing:
    - $ref: dev:my-default-routing:1.0