#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: 'HTTPEndpoint'
apiVersion: api.webmethods.io/beta
metadata:
  name: default_endpoint
  version: "beta"
  namespace: dev
spec:
  url: http://test.com
  method: GET
  connectTimeout: 300
  readTimeout: 200
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    truststoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""