kind: Environment
metadata:
  name: TestProductEnvironment
  version: 1.0
  tags:
    - payEnv
  namespace: dev
spec:
  variables:
    - key: "X-Gateway-APIKey"
      value: "${X-Gateway-APIKey}" 
      isSecret: true