kind: api
apiVersion: api.webmethods.io/v1
metadata:
  name: FromMain
  namespace: dev
  version: 1.0
  tags:
    - swagger
    - daso
    - sample
  type: REST
spec:
  mocked: true
  api-spec:
    $path: petstore.yaml
  policy-sequence:
    - $ref: dev:dev_policies:1.0
