#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: api
apiVersion: api.webmethods.io/v1
metadata:
  name: swagger_petstore_testcli
  namespace: dev
  version: 1.0
  tags:
    - swagger
    - daso
    - sample
  type: REST
spec:
  api-spec: 
    $path: swagger_petstore.yaml
  policy-seq: 
    - $ref: policies:my_policies:1.0